/**
 * Blog render styles.
 */

export function archiveStyles() {
  return `:root{--ink:#0f172a;--muted:#6b7280;--card:#ffffff;--border:#e5e7eb;--accent:#0ea5e9;--accent-2:#e2e8f0;}body{font-family:'Space Grotesk',system-ui,-apple-system,sans-serif;background:radial-gradient(1200px 600px at 10% -10%, #f8fafc 0%, #f1f5f9 40%, #ffffff 100%);color:var(--ink);margin:0}.wrap{max-width:1200px;margin:0 auto;padding:40px 20px}h1{margin:0 0 10px;font-size:36px;font-family:'Cormorant Garamond',serif;letter-spacing:0.5px}.sub{color:var(--muted);margin:0 0 28px;font-size:16px}.layout{display:grid;grid-template-columns:1.2fr 0.8fr;gap:28px;align-items:start}.list{display:flex;flex-direction:column;gap:16px}.post{display:block;text-decoration:none;background:var(--card);border:1px solid var(--border);border-radius:18px;padding:18px 20px;box-shadow:0 6px 20px rgba(15,23,42,0.06);transition:transform .2s,border-color .2s,box-shadow .2s}.post:hover{border-color:#bae6fd;transform:translateY(-2px);box-shadow:0 12px 24px rgba(15,23,42,0.12)}.title{font-weight:700;color:var(--ink);font-size:20px}.meta{color:var(--muted);font-size:13px;margin-top:6px}.desc{color:#334155;font-size:15px;line-height:1.5;margin-top:10px;display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;overflow:hidden}.read{margin-top:12px;color:var(--accent);font-weight:600;font-size:14px}.side{background:var(--card);border:1px solid var(--border);border-radius:18px;padding:18px 18px;position:sticky;top:20px;box-shadow:0 6px 20px rgba(15,23,42,0.06)}.side h3{margin:0 0 12px;font-size:18px}.side-links{display:flex;flex-direction:column;gap:12px}.side-link{text-decoration:none;border:1px solid var(--accent-2);border-radius:12px;padding:10px 12px;display:block}.side-link:hover{border-color:#bae6fd;background:#f8fafc}.side-title{font-weight:600;color:var(--ink);font-size:14px}.side-date{color:var(--muted);font-size:12px;margin-top:4px}.cta{margin-top:16px;padding:12px 14px;border-radius:12px;border:1px dashed #bae6fd;background:#f0f9ff;color:#0f172a;font-size:14px}.cta a{color:var(--accent);text-decoration:none;font-weight:600}.hero{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;gap:12px;flex-wrap:wrap}.submit{display:inline-block;padding:10px 14px;border-radius:10px;border:1px solid #e2e8f0;text-decoration:none;color:#0f172a;background:#fff}.submit:hover{border-color:#bae6fd}@media (max-width: 900px){.layout{grid-template-columns:1fr}.side{position:static}}@media (max-width: 600px){h1{font-size:30px}}`;
}

export function submitStyles() {
  return `body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f9fafb;color:#111827;margin:0}.wrap{max-width:900px;margin:0 auto;padding:28px 18px}a{color:inherit}.back{display:inline-block;margin-bottom:16px;color:#6b7280;text-decoration:none}.back:hover{text-decoration:underline}.card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:16px}label{display:block;font-weight:600;margin-bottom:6px}input,textarea{width:100%;padding:10px;border:1px solid #d1d5db;border-radius:8px;font-family:inherit}textarea{min-height:160px;resize:vertical}.btn{padding:10px 16px;border:0;border-radius:8px;background:#111827;color:#fff;font-weight:600;cursor:pointer}.note{color:#6b7280;font-size:13px;margin-top:8px}.msg{margin-top:10px;font-size:14px}`;
}

export function postStyles() {
  return `body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#fff;color:#111827;margin:0}.wrap{max-width:900px;margin:0 auto;padding:28px 18px}a{color:inherit}.back{display:inline-block;margin-bottom:16px;color:#6b7280;text-decoration:none}.back:hover{text-decoration:underline}`;
}
